---
title: "CIARA_main_figures"
author: "Gabriele Lubatti"
date: "7/4/2022"
output: html_document
---



```{r }
gc()
rm(list=ls())
```


```{r } 
#devtools::install_github("ScialdoneLab/CIARA",auth_token="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",ref="master")
```



```{r }
library(CIARA)
library(Seurat)
library(gplots)
library(ggplot2)
library("mltools")
library(FiRE)
library(clustree)
```

## Function
```{r }
find_positive_cells=function(norm_elmir_5_30,geni_marker,threshold){

logic_cell=apply(norm_elmir_5_30[geni_marker,],2,function(x){
  
  if (sum(x>threshold)==length(x))
  {return(TRUE)}
  else{return(FALSE)}
})
positive_cells=colnames(norm_elmir_5_30)[logic_cell]
return(positive_cells)
}



```
## Download files
```{r}
current_wd <- getwd()
url="https://hmgubox2.helmholtz-muenchen.de/index.php/s/x83jDLHobM7Qer6/download/CIARA.zip"

destfile <- paste0(current_wd,"/CIARA.zip")
download.file(url, destfile, quiet = FALSE)
unzip(destfile, exdir=current_wd)
```

```{r }
setwd(paste0(current_wd,"/CIARA"))
load(file='mayra_dati_raw_0.Rda')
mayra_seurat_0=cluster_analysis_integrate_rare(mayra_dati_raw_0,"Mayra_data_0",0.1,5,30)
norm_counts_ane_0=as.matrix(GetAssayData(mayra_seurat_0, slot = "data",assay="RNA"))
knn_matrix_ane_0=as.matrix(mayra_seurat_0@graphs$RNA_nn)
cordinate_umap_0=as.data.frame(Embeddings(mayra_seurat_0, reduction = "umap")[, 1:2])
```

## Run CIARA
```{r }
#norm_matrix=norm_counts_ane_0
#knn_matrix=knn_matrix_ane_0
#background <- get_background_full(norm_matrix, threshold = 1, n_cells_low = 3, n_cells_high = 20)
#result <- CIARA(norm_matrix, knn_matrix, background, cores_number = 1, p_value = 0.001, local_region = 1, approximation = FALSE)

setwd(paste0(current_wd,"/CIARA"))
load("result_ane_0.Rda")
```



```{r }
ciara_genes=row.names(result)[result[,1]<1]
geni_top_top=row.names(result)[order(as.numeric(result[,1]))]
background=row.names(result)
```

## Figure 1b
```{r }
localized_genes_mouse=detect_localized_genes(knn_matrix_ane_0,norm_counts_ane_0,geni_top_top,100) 
rank_intersect=localized_genes_mouse[[2]]
list_intersect=localized_genes_mouse[[1]]

ramp <- colorRamp(c("white", "blue4"))




ramp <- colorRamp(c("white", "blue4"))
 

rank_intersect=localized_genes_mouse[[2]]
list_intersect=localized_genes_mouse[[1]]


ramp.list <- rgb( ramp(seq(0, 1, length = length(unique(rank_intersect)))), max = 255)

index_color=round(length(ramp.list)/2,0)


breaks = seq(0,max(rank_intersect),length.out=1000)
gradient1 = colorpanel( sum( breaks[-1]<= as.numeric(quantile(breaks,0.25))), "#FFFFFF",ramp.list[index_color])

gradient2 = colorpanel( sum( breaks[-1] > as.numeric(quantile(breaks,0.25)) ), ramp.list[index_color], "#00008B" )


hm.colors = c(gradient1,gradient2)
 





genes_name_text=names_localized_genes(list_intersect ,geni_top_top,max_number=5)


plot_localized_genes_interactive(cordinate_umap_0,norm_counts_ane_0,rank_intersect,genes_name_text,hm.colors,min_x=NULL,max_x=NULL,min_y=NULL,max_y=NULL)



plot_localized_genes(cordinate_umap_0,norm_counts_ane_0,rank_intersect,"Top 100 genes CIARA",hm.colors)+theme_bw()+theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+theme(text = element_text(size=12))+geom_point( alpha = 0.3, na.rm = T, shape = 21, colour = "black",stroke=0.1)







```
```{r }
mayra_0_ciara=cluster_analysis_integrate_rare(mayra_dati_raw_0,"Mayra data",0.1,5,30,ciara_genes)


```


## Figure 1C
```{r }
mayra_0_ciara=FindClusters(mayra_0_ciara,resolution = 0.1)
p=plot_umap(cordinate_umap_0,as.vector(mayra_0_ciara$RNA_snn_res.0.1))
p[[1]]+theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+theme(text = element_text(size=18))


```




## Figure 2b

### FiRE

```{r }
setwd(paste0(current_wd,"/CIARA"))
load(file="data.Rda")
setwd(paste0(current_wd,"/CIARA"))
labels <- read.table('/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/published_data/FiRE-master/data/labels_jurkat_two_species_1580.txt')
labels=labels$V1
```




```{r }
setwd(paste0(current_wd,"/CIARA"))
load("fire.Rda")
```


```{r }
ciara_genes=row.names(result)[result[,1]<1]
geni_top_top=row.names(result)[order(as.numeric(result[,1]))]
background=row.names(result)
```

```{r }
fire_ciara=cluster_analysis_integrate_rare(data,"24h",0.1,3,30,ciara_genes)
```

```{r }

norm_fire_ciara=as.matrix(GetAssayData(fire_ciara, slot = "data",assay="RNA"))
cluster_fire_ciara=as.vector(fire_ciara$RNA_snn_res.0.1)

```



```{r }
setwd(paste0(current_wd,"/CIARA"))
source("preprocess.R")

data_example <- t(data)
genes <- colnames(data_example)

data_mat <- list(mat=data_example, gene_symbols=genes)

preprocessedList <- ranger_preprocess(data_mat)
preprocessedData <- as.matrix(preprocessedList$preprocessedData)

model <- new(FiRE::FiRE, 100, 50, 1017881, 5489, 0)

model$fit(preprocessedData)

score <- model$score(preprocessedData)
q3 <- quantile(score, 0.75)
iqr <- IQR(score)
th <- q3 + (1.5*iqr)
indIqr <- which(score >= th)
predictions <- integer(dim(data_example)[1])
predictions[indIqr] <- 1 


```

```{r }

#mcc()
#Matthews correlation coefficient 

preds=as.numeric(cluster_fire_ciara)
actuals=as.numeric(labels)
actuals_new=actuals
actuals_new[actuals==2]=1
actuals_new[actuals==1]=0


mcc(preds, actuals_new)



mcc(predictions, actuals_new)
```




```{r }

method=factor(c("CIARA","FiRE"),levels=c(c("CIARA","FiRE")))
df=data.frame(c(0.95,0.74),method)
colnames(df)=c("MCC","Method")
ggplot(data=df, aes(x=Method, y=MCC, fill=Method)) +
  geom_bar(stat="identity", width=0.5)+ylim(0,1)+ggtitle("MCC score")+scale_fill_manual(values=c(CIARA:::gg_color_hue(2)))

```


## CellSIUS

```{r }
setwd(paste0(current_wd,"/CIARA"))
load(file="raw_sce_small.Rda")
load(file="cell_line_all.Rda")

```


```{r }
setwd(paste0(current_wd,"/CIARA"))
load("cellsius.Rda")
```



```{r }
ciara_genes=row.names(result)[result[,1]<1]
geni_top_top=row.names(result)[order(as.numeric(result[,1]))]
background=row.names(result)
```


```{r }

cellsius_ciara=cluster_analysis_integrate_rare(raw_sce_small,"24h",0.1,3,30,(ciara_genes))


```




```{r }
norm_cellsius_ciara=as.matrix(GetAssayData(cellsius_ciara, slot = "data",assay="RNA"))
cluster_cellsius_ciara=as.vector(cellsius_ciara$RNA_snn_res.0.1)
```


```{r }

#mcc()
#Matthews correlation coefficient 

preds=as.numeric(cluster_cellsius_ciara)[cluster_cellsius_ciara==7|cluster_cellsius_ciara==8]
actuals=as.numeric(cell_line_all)[cluster_cellsius_ciara==7|cluster_cellsius_ciara==8]

actuals_new=actuals
actuals_new[actuals==8]=7
actuals_new[actuals==5]=8

mcc(preds, actuals_new)





```
```{r }
method=factor(c("CIARA","CellSIUS"),levels=c(c("CIARA","CellSIUS")))
df=data.frame(c(1,1),method)
colnames(df)=c("MCC","Method")
ggplot(data=df, aes(x=Method, y=MCC, fill=Method)) +
  geom_bar(stat="identity", width=0.5)+ylim(0,1)+ggtitle("MCC score")+scale_fill_manual(values=c(CIARA:::gg_color_hue(2)))

```

## GiniClust

```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/vignettes")
load("gini_fig_5.Rda")
```




```{r }
ciara_genes=row.names(result)[result[,1]<1]
geni_top_top=row.names(result)[order(as.numeric(result[,1]))]
background=row.names(result)
```



```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/published_data")
load("test_data_3.Rda")
#load(file="norm_gini_3.Rda")
#load(file="knn_matrix_gini_5_30_3.Rda")
#load(file="cordinate_gini_3.Rda")
setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/published_data")
gini_cluster_3=read.csv2("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/published_data/13059_2016_1010_MOESM11_ESM.csv")

gini_name_3=gini_cluster_3$Cell.ID
gini_cluster_3=gini_cluster_3$Cluster.ID
ordine=data.frame(gini_name_3,gini_cluster_3)
row.names(ordine)=gini_name_3
gini_cluster_3=ordine[colnames(test_data_3),2]
```

```{r }
gini_ciara=cluster_analysis_integrate_rare(test_data_3,"24h",0.1,3,30,ciara_genes)
```


```{r }

norm_gini_ciara=as.matrix(GetAssayData(gini_ciara, slot = "data",assay="RNA"))

cluster_gini_ciara=as.vector(gini_ciara$RNA_snn_res.0.1)

```


```{r }
geni_marker=c("CLDN11","MBP","PLP1","KLK6")
positive_cells=find_positive_cells(norm_gini_ciara,geni_marker,threshold = 0)
```




```{r }

ciara_score=rep(0,length(gini_cluster_3))
method_score=rep(0,length(gini_cluster_3))
original_score=rep(0,length(gini_cluster_3))

method_score[gini_cluster_3=="Cluster_3"]=1
ciara_score[as.vector(gini_ciara$RNA_snn_res.0.1)==10]=1
original_score[colnames(norm_gini_ciara)%in%positive_cells]=1


mcc(ciara_score, original_score)

mcc(method_score, original_score)


```

```{r }
library(ggplot2)
library(CIARA)
method=factor(c("CIARA","GiniClust"),levels=c(c("CIARA","GiniClust")))
df=data.frame(c(0.74,0.66),method)
colnames(df)=c("MCC","Method")

ggplot(data=df, aes(x=Method, y=MCC, fill=Method)) +
  geom_bar(stat="identity", width=0.5)+ylim(0,1)+ggtitle("MCC score")+scale_fill_manual(values=c(CIARA:::gg_color_hue(2)))

```

## GiniClust2

```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/published_data")
load("finalCluster.Rda")
load("giniclust2.Rda")

#norm_gini2=(GetAssayData(giniclust2, slot = "data",assay="RNA"))
raw_gini2=(GetAssayData(giniclust2, slot = "data",assay="RNA"))
#setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/published_data")
#save(norm_gini2,file="norm_gini2.Rda")

#general_cluster_gini=giniclust2$RNA_snn_res.0.1


#knn_matrix_gini=(giniclust2@graphs$RNA_nn)

#setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/published_data")
#knn_matrix_gini2=knn_matrix_gini
#save(knn_matrix_gini2,file="knn_matrix_gini2.Rda")

#cordinate_umap_gini=as.data.frame(Embeddings(giniclust2, reduction = "umap")[, 1:2])

```

```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/vignettes")
load("gini2.Rda")
```


```{r }
ciara_genes=row.names(result)[result[,1]<1]
geni_top_top=row.names(result)[order(as.numeric(result[,1]))]
background=row.names(result)
```

```{r }
giniclu2_ciara=cluster_analysis_integrate_rare(raw_gini2,"24h",0.3,5,30,ciara_genes)

cluster_gini2_ciara=as.vector(giniclu2_ciara$RNA_snn_res.0.3)
```


```{r }
norm_gini2=as.matrix(GetAssayData(giniclu2_ciara, slot = "data",assay="RNA"))

geni_marker_1=c("Col4a1","Col4a2","Lama1","Ctsl")

geni_marker_2=c("Rhox6","Rhox9","Sct")
positive_cells_1=find_positive_cells(norm_gini2,geni_marker_1,threshold = 0)
positive_cells_2=find_positive_cells(norm_gini2,geni_marker_2,threshold = 0)

```







```{r }


method_score=rep(0,length(colnames(norm_gini2)))
ciara_score=rep(0,length(colnames(norm_gini2)))
original_score=rep(0,length(colnames(norm_gini2)))
original_score[colnames(norm_gini2)%in%positive_cells_1]=1
method_score[finalCluster==1]=1
ciara_score[cluster_gini2_ciara==2]=1

mcc(ciara_score,original_score)


mcc(method_score,original_score)




method_score=rep(0,length(colnames(norm_gini2)))
ciara_score=rep(0,length(colnames(norm_gini2)))
original_score=rep(0,length(colnames(norm_gini2)))
original_score[colnames(norm_gini2)%in%positive_cells_2]=1
method_score[finalCluster==2]=1
ciara_score[cluster_gini2_ciara==1]=1

mcc(ciara_score,original_score)


mcc(method_score,original_score)


```
```{r }
library(ggplot2)
library(CIARA)
method=factor(c("CIARA","GiniClust2"),levels=c(c("CIARA","GiniClust2")))
df=data.frame(c(0.7398754,0.7398754),method)
colnames(df)=c("MCC","Method")
ggplot(data=df, aes(x=Method, y=MCC, fill=Method)) +
  geom_bar(stat="identity", width=0.5)+ylim(0,1)+ggtitle("MCC score")+scale_fill_manual(values=c(CIARA:::gg_color_hue(2)))

```

```{r }
library(ggplot2)
library(CIARA)
method=factor(c("CIARA","GiniClust2"),levels=c(c("CIARA","GiniClust2")))
df=data.frame(c(0.8911083,0.7019264),method)
colnames(df)=c("MCC","Method")

ggplot(data=df, aes(x=Method, y=MCC, fill=Method)) +
  geom_bar(stat="identity", width=0.5)+ylim(0,1)+ggtitle("MCC score")+scale_fill_manual(values=c(CIARA:::gg_color_hue(2)))

```


```{r }

```





