---
title: "Human Gastrula Data"
author: "Gabriele Lubatti"
date: "3/30/2021"
output: html_document
---



```{r } 
gc()
rm(list=ls())
library(devtools)
#install_github("ScialdoneLab/CIARA",auth_token="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",ref="master")
#library(devtools)
#install_github("ScialdoneLab/IDENTOM",auth_token="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",ref="master")
```

```{r } 
library(destiny)#Not necessary for IDENTOM
#library(Biobase)
#library(Seurat)
#library(clustree)
#library(plotly)
#library(ggplot2)

#library(DescTools)
#library(rlist)
#library(parallel)
```

```{r } 
library(CIARA)
library(Seurat)
library(clustree)
```




## Start with Human gastrula data




```{r }
load(system.file("extdata", "raw_elmir_5_30.Rda", package ="CIARA"))

umap_elmir=readRDS(system.file("extdata", "annot_umap.rds", package ="CIARA"))

setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/elmir_data")
write.csv(umap_elmir,"umap_elmir.csv")




```

```{r }

setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/CIARA_archive/CIARA_old/inst/extdata")
diff_map_endo=read.csv("endo_diffmap.csv")
diff_map_hema=read.csv("hep_diffmap_coord.csv")
#diff_map_endo=read.csv(system.file("extdata", "endo_diffmap.csv", package ="CIARA"))

#diff_map_hema=read.csv(system.file("extdata", "hep_diffmap_coord.csv", package ="CIARA"))

```

```{r }

setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/CIARA_archive/CIARA_old/inst/extdata")
spatial_annotation=read.table("spatial_annotation.txt")

#spatial_annotation=read.table(system.file("extdata", "spatial_annotation.txt", package ="CIARA"))
origin_space=spatial_annotation[,2]
```


```{r }

elmir_seurat_5=cluster_analysis_integrate_rare(raw_elmir_5_30,"Elmir_data",0.1,5,30)


```








```{r }

norm_elmir_5_30=as.matrix(GetAssayData(elmir_seurat_5, slot = "data",assay="RNA"))


general_cluster_version_elmir=elmir_seurat_5$RNA_snn_res.0.1


knn_matrix_elmir_5_30=as.matrix(elmir_seurat_5@graphs$RNA_nn)

cordinate_umap=umap_elmir[,2:3]

setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/published_data")
save(knn_matrix_elmir_5_30,file="knn_matrix_elmir_5_30.Rda")
save(norm_elmir_5_30,file="norm_elmir_5_30.Rda")


```




## Cluster provided by Tyser et al, 2020


```{r }

original_cluster=as.vector(umap_elmir$cluster_id)
names(original_cluster)=names(elmir_seurat_5$RNA_snn_res.0.1)
plot_umap(cordinate_umap,original_cluster)
```

```{r }
#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/elmir_data/entropy_hyper_server_all_cells.R -n norm_elmir_5_30 -k knn_matrix_elmir_5_30 -o elmir_hyper_old_test.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001
#2.438366 mins

#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/elmir_data/entropy_hyper_server_blood_new.R -n norm_elmir_5_30 -k knn_matrix_elmir_5_30 -o elmir_hyper_new.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001
#Time difference of 1.058072 mins


##LAST VERSION (setting srun -p normal_q -c 10  --mem=10G -t 1:00:00 --pty bash)
#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/elmir_data/entropy_server_december_2021_new.R -n norm_elmir_5_30 -k knn_matrix_elmir_5_30 -o elmir_december_2021.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001 -c 10 -a FALSE
#Time difference of 6.323627 mins 1.647605 mins

#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/elmir_data/entropy_server_december_2021_new.R -n norm_elmir_5_30 -k knn_matrix_elmir_5_30 -o elmir_december_2021_a.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001 -c 10 -a TRUE
#Time difference of 1.647605 mins




```


```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/CIARA_archive/CIARA_old/inst/extdata")
load("elmir_december_2021.Rda")
#load(system.file("extdata", "elmir_december_2021.Rda", package ="CIARA"))


#load("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/elmir_december_2021.Rda")
```



```{r }
#ciara_genes=row.names(result)[result[,2]<1]
#geni_top=row.names(result)[result[,2]<0.0001&result[,1]==0]
#geni_top_top=row.names(result)[order(as.numeric(result[,2]))]
```

```{r }
ciara_genes=row.names(result)[result[,1]<1]
#geni_top=row.names(result)[result[,1]==0&result[,2]<0.0001]
geni_top_top=row.names(result)[order(as.numeric(result[,1]))]
```


```{r }

p=list()
for(i in (geni_top_top)[1:10]){
  q=plot_gene(norm_elmir_5_30,cordinate_umap,i,i)
  p=list(p,q)
}
p
```

```{r }
background=row.names(result)
```



```{r }
plot_genes_sum(cordinate_umap,norm_elmir_5_30,(ciara_genes),"Sum from top CIARA genes")

```


```{r }
norm_counts_small = apply(norm_elmir_5_30[(ciara_genes), ], 
        1, function(x) {
            y = x/sum(x)
            return(y)
        })
    gene_sum = apply(norm_counts_small, 1, sum)
    
    
#genes_name_text=selection_localized_genes_here(norm_elmir_5_30,ciara_genes,min_number_cells=4,max_number_genes=4)
genes_name_text=selection_localized_genes(norm_elmir_5_30,ciara_genes,min_number_cells=4,max_number_genes=4)
plot.elmir=umap_elmir[,2:3]
colnames(plot.elmir)=c("UMAP_1","UMAP_2")
plot_interactive(plot.elmir,gene_sum,genes_name_text,min_x=NULL,max_x=NULL,min_y=NULL,max_y=NULL)
```









## Cluster analysis using CIARA (step 2)
```{r }
elmir_seurat_ciara=cluster_analysis_integrate_rare(raw_elmir_5_30,"Elmir data",0.01,5,30,(ciara_genes))

```

```{r }
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/sup_figure_1/sup_figure_1_a.pdf")
find_resolution(elmir_seurat_ciara,seq(0.01,1,0.1))
dev.off()
```


```{r }

norm_elmir_ciara_5_30=as.matrix(GetAssayData(elmir_seurat_ciara, slot = "data",assay="RNA"))



cordinate_umap_ciara=as.data.frame(Embeddings(elmir_seurat_ciara, reduction = "umap")[, 1:2])


```




```{r }
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_2/figure_2_j.pdf")
plot_umap(cordinate_umap,elmir_seurat_ciara$RNA_snn_res.0.01)
dev.off()
plot_gene(norm_elmir_ciara_5_30,cordinate_umap,"NANOS3","NANOS3")
plot_gene(norm_elmir_ciara_5_30,cordinate_umap,"NANOG","NANOG")
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/sup_figure_1/sup_figure_1_b.pdf")
plot_gene(norm_elmir_ciara_5_30,cordinate_umap,"SOX17","SOX17")
dev.off()
plot_gene(norm_elmir_ciara_5_30,cordinate_umap,"DPPA5","DPPA5")





```


```{r}
original_sub_cluster=umap_elmir$sub_cluster
original_cluster_plot=rep("Other clusters",length(original_sub_cluster))
original_cluster_plot[original_sub_cluster=="PGC"]="PGC"
original_cluster_plot[original_sub_cluster=="Axial Mesoderm"]="Axial Mesoderm"
original_cluster_plot=factor(original_cluster_plot ,levels=c("Other clusters","Axial Mesoderm","PGC"))
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_2/figure_2_i.pdf")
plot_umap(cordinate_umap,original_cluster_plot)
dev.off()

```


## Cluster analysis using CIARA (step 3)

```{r}
final_cluster=merge_cluster(original_cluster,elmir_seurat_ciara$RNA_snn_res.0.01,20)
```

```{r}
final_cluster[final_cluster=="2-step_2"]="PGC"
```


```{r}
DefaultAssay(elmir_seurat_5) <- "RNA"
markers_first_elmir=markers_cluster_seurat(elmir_seurat_5,final_cluster,names(elmir_seurat_5$RNA_snn_res.0.1),5)

markers_first_elmir_1=markers_first_elmir[[1]]
markers_first_elmir_3=markers_first_elmir[[3]]
```

```{r }
plot_umap(cordinate_umap,final_cluster)
```

```{r}


white_black_7=white_black_markers(final_cluster,"PGC",norm_elmir_5_30,markers_first_elmir_3,0)
sum(white_black_7)

```










## Cluster analysis using CIARA  (step 4)



```{r }
##For having just two rare cells population
#result_test=test_hvg(raw_elmir_5_30,final_cluster,(ciara_genes),background,100,0.001)
result_test=test_hvg(raw_elmir_5_30,final_cluster,(ciara_genes),background,100,0.05)

```



```{r }
result_test[[2]]
```







```{r }
raw_elmir=as.matrix(GetAssayData(elmir_seurat_5, slot = "counts",assay="RNA"))
raw_endoderm=raw_elmir[,as.vector(umap_elmir$cluster_id)=="Endoderm"]
raw_emo=raw_elmir[,as.vector(umap_elmir$cluster_id)=="Hemogenic Endothelial Progenitors"]
raw_exe_meso=raw_elmir[,as.vector(umap_elmir$cluster_id)=="ExE Mesoderm"]



combined_endoderm=cluster_analysis_sub(raw_endoderm,0.2,5,30,"Endoderm")

combined_emo=cluster_analysis_sub(raw_emo,0.6,5,30,"Hemogenic Endothelial Progenitors")

combined_exe_meso=cluster_analysis_sub(raw_exe_meso,0.5,5,30,"ExE Mesoderm")





```




```{r }

all_sub_cluster=c(combined_endoderm$seurat_clusters,combined_emo$seurat_clusters,combined_exe_meso$seurat_clusters)
final_cluster_version_sub=merge_cluster(final_cluster,all_sub_cluster)
```

```{r}
load("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/elmir_data/final_cluster_version_sub.Rda")
```

```{r}
plot_umap(umap_elmir[,2:3],umap_elmir$sub_cluster)
plot_umap(umap_elmir[,2:3],umap_elmir$cluster_id)
```

```{r}
plot_umap(umap_elmir[,2:3],final_cluster_version_sub)
```



```{r}
table(as.vector(final_cluster_version_sub))
```















## CIARA identifies a population of cells with highly distinctive transcriptional profile 

```{r}
DefaultAssay(elmir_seurat_5) <- "RNA"
markers_first_elmir_final=markers_cluster_seurat(elmir_seurat_5,final_cluster_version_sub,names(elmir_seurat_5$RNA_snn_res.0.1),5)

markers_first_elmir_1_final=markers_first_elmir_final[[1]]
markers_first_elmir_3_final=markers_first_elmir_final[[3]]
```




```{r}
white_black_7=white_black_markers(final_cluster_version_sub,"Hemogenic Endothelial Progenitors_4",norm_elmir_5_30,markers_first_elmir_3_final,0)
sum(white_black_7)

```

```{r}
white_black_7=white_black_markers(final_cluster_version_sub,"Endoderm_2",norm_elmir_5_30,markers_first_elmir_3_final,0)
sum(white_black_7)
```

```{r}
white_black_7=white_black_markers(final_cluster_version_sub,"ExE Mesoderm_0",norm_elmir_5_30,markers_first_elmir_3_final,0)
sum(white_black_7)
```

```{r}

top_endo=white_black_markers(final_cluster_version_sub,"Endoderm_2",norm_elmir_5_30,markers_first_elmir_3_final,0)
top_endo=names(top_endo)[top_endo]


mean_top_endo=apply(norm_elmir_5_30[top_endo,final_cluster_version_sub=="Endoderm_2"],1,mean)
mean_top_endo=sort(mean_top_endo,decreasing = T)

top_endo=names(mean_top_endo)
names(top_endo)=rep("Endoderm_2",length(top_endo))

```

```{r}

top_hemo=white_black_markers(final_cluster_version_sub,"Hemogenic Endothelial Progenitors_4",norm_elmir_5_30,markers_first_elmir_3_final,0)
top_hemo=names(top_hemo)[top_hemo]


mean_top_hemo=apply(norm_elmir_5_30[top_hemo,final_cluster_version_sub=="Hemogenic Endothelial Progenitors_4"],1,mean)
mean_top_hemo=sort(mean_top_hemo,decreasing = T)

top_hemo=names(mean_top_hemo)
names(top_hemo)=rep("Hemogenic Endothelial Progenitors_4",length(top_hemo))
```

```{r}
top_meso=white_black_markers(final_cluster_version_sub,"ExE Mesoderm_1",norm_elmir_5_30,markers_first_elmir_3_final,0)
top_meso=names(top_meso)[top_meso]


mean_top_meso=apply(norm_elmir_5_30[top_meso,final_cluster_version_sub=="ExE Mesoderm_1"],1,mean)
mean_top_meso=sort(mean_top_meso,decreasing = T)

top_meso=names(mean_top_meso)
names(top_meso)=rep("ExE Mesoderm_1",length(top_meso))



```


```{r}



toMatch=c("Endoderm")
#Plot_balons(norm_elmir_5_30[,grep(paste(toMatch,collapse="|"),final_cluster)],final_cluster_version_sub[grep(paste(toMatch,collapse="|"),final_cluster)],markers_first_elmir_3_final[names(markers_first_elmir_3_final)=="Endoderm_2"],20,max_size=5,text_size=10)

pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_4/figure_4_c.pdf")
plot_balloon_marker(norm_elmir_5_30[,grep(paste(toMatch,collapse="|"),final_cluster)],final_cluster_version_sub[grep(paste(toMatch,collapse="|"),final_cluster)],top_endo,20,max_size=5,text_size=10)
dev.off()

pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_4/figure_4_f.pdf")
toMatch=c("Hemogenic Endothelial Progenitors")
plot_balloon_marker(norm_elmir_5_30[,grep(paste(toMatch,collapse="|"),final_cluster)],final_cluster_version_sub[grep(paste(toMatch,collapse="|"),final_cluster)],top_hemo,20,max_size=5,text_size=8)
dev.off()

toMatch=c("ExE Mesoderm")
plot_balloon_marker(norm_elmir_5_30[,grep(paste(toMatch,collapse="|"),final_cluster)],final_cluster_version_sub[grep(paste(toMatch,collapse="|"),final_cluster)],top_meso,length(top_meso),max_size=5,text_size=8)



```







```{r }

plot_gene(norm_elmir_5_30,cordinate_umap,"C1R","C1R")
plot_gene(norm_elmir_5_30,cordinate_umap,"NANOS3","NANOS3")
plot_gene(norm_elmir_5_30,cordinate_umap,"NANOG","NANOG")
plot_gene(norm_elmir_5_30,cordinate_umap,"SOX17","SOX17")
plot_gene(norm_elmir_5_30,cordinate_umap,"DPPA5","DPPA5")
plot_gene(norm_elmir_5_30,cordinate_umap,"CSF1","CSF1")
```



```{r}
original_cluster_plot=rep("Other clusters",length(original_cluster))
original_cluster_plot[original_cluster=="Endoderm"]="Endoderm"
original_cluster_plot[original_cluster=="Hemogenic Endothelial Progenitors"]="Hemogenic Endothelial Progenitors"
original_cluster_plot[original_cluster=="ExE Mesoderm"]="ExE Mesoderm"
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_4/figure_4_a.pdf")
plot_umap(cordinate_umap,original_cluster_plot)
dev.off()


original_cluster_plot=rep("Other clusters",length(final_cluster_version_sub))
original_cluster_plot[grep("Endoderm",final_cluster_version_sub)]=final_cluster_version_sub[grep("Endoderm",final_cluster_version_sub)]

original_cluster_plot[grep("Hemogenic Endothelial Progenitors",final_cluster_version_sub)]=final_cluster_version_sub[grep("Hemogenic Endothelial Progenitors",final_cluster_version_sub)]
original_cluster_plot[grep("ExE Mesoderm",final_cluster_version_sub)]=final_cluster_version_sub[grep("ExE Mesoderm",final_cluster_version_sub)]
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_4/figure_4_b.pdf")
plot_umap(cordinate_umap,original_cluster_plot)
dev.off()



```

##Start diffusion map analysis





```{r }

diff_map_elmir=diff_map_hema[,3:4]
cell_diff=diff_map_hema$cell_name
umap_elmir_diff=umap_elmir
row.names(umap_elmir_diff)=umap_elmir$cell_name

original_sub_cluster_diff=umap_elmir_diff[cell_diff,]$sub_cluster
plot_umap(diff_map_elmir,original_sub_cluster_diff)


data_diff=data.frame(final_cluster_version_sub,colnames(norm_elmir_5_30))
row.names(data_diff)=colnames(norm_elmir_5_30)
sub_cluster_diff=data_diff[cell_diff,1]
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_4/figure_4_i.pdf")
plot_umap(diff_map_elmir,sub_cluster_diff) 
dev.off()
```


```{r }
diff_map_elmir_endo=diff_map_endo[,2:4]
diff_map_elmir_endo=diff_map_elmir_endo[,-2]

umap_elmir_diff=umap_elmir
row.names(umap_elmir_diff)=umap_elmir$cell_name

cells_endo=as.vector(umap_elmir$cell_name[umap_elmir$cluster_id=="Endoderm"])

original_sub_cluster_diff=umap_elmir_diff[cells_endo,]$sub_cluster
plot_umap(diff_map_elmir_endo,original_sub_cluster_diff) 


data_diff=data.frame(final_cluster_version_sub,colnames(norm_elmir_5_30))
row.names(data_diff)=colnames(norm_elmir_5_30)
sub_cluster_diff=data_diff[cells_endo,1]
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_4/figure_4_d.pdf")
plot_umap(diff_map_elmir_endo,sub_cluster_diff) 
dev.off()



```



```{r }

original_cluster=umap_elmir$cluster_id
names(original_cluster)=colnames(raw_elmir_5_30)
cluster_diff_exe=original_cluster[original_cluster=="ExE Mesoderm"]
raw_elmir=as.matrix(GetAssayData(elmir_seurat_5, slot = "counts",assay="RNA"))

raw_exe=raw_elmir[,original_cluster=="ExE Mesoderm"]

batch_1 <- CreateSeuratObject(counts = raw_endoderm, project = "Endoderm")
    batch_1 <- subset(batch_1, subset = nFeature_RNA > 0)
    batch_1 <- NormalizeData(batch_1, verbose = FALSE)
    batch_1 <- FindVariableFeatures(batch_1, selection.method = "vst", 
        nfeatures = 2000)
    hvg_endo=batch_1@assays$RNA@var.features
    
    raw_endoderm_sub=raw_exe[hvg_endo,]
    
    dm <- DiffusionMap(t(raw_endoderm_sub))
diff_map_endo <- as.data.frame(cbind(DC1 = dm$DC1, DC2 = dm$DC2))


plot_umap(diff_map_endo,umap_elmir$sub_cluster[original_cluster=="ExE Mesoderm"]) 

plot_umap(diff_map_endo,final_cluster_version_sub[original_cluster=="ExE Mesoderm"])

```

