---
title: "Mouse_after_gastrula"
author: "Gabriele Lubatti"
date: "10/21/2021"
output:
  html_document: default
  pdf_document: default
---


```{r } 
gc()
rm(list=ls())
#library(devtools)
#install_github("ScialdoneLab/CIARA",auth_token="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",ref="master")
```

```{r } 
#library(Seurat)
#library(clustree)
#library(plotly)
#library(ggplot2)
#library(CIARA)
```


```{r } 
library(CIARA)
library(UpSetR)
library(Seurat)
```










```{r }
geni_ortogoli_unique=function(rabbit_id,name_mouse){

#setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Rabbit/10x_data/Processed_data/Radius_of_gyration")

name_mouse=name_mouse[isUnique(as.vector(name_mouse$initial_ensg))&isUnique(as.vector(name_mouse$ortholog_name)),]
marker_plot_all_1=rabbit_id[rabbit_id%in%name_mouse$initial_ensg]
name_rabbit=as.vector(name_mouse$ortholog_name)
name_rabbit[name_rabbit=="N/A"]=as.vector(name_mouse$initial_ensg[name_rabbit=="N/A"])

#setwd(paste0(base_path,"10x_data/Output_script"))
#name_mouse=read.csv(file=geni_ortogoli_g_profiler)
#name_mouse_no=name_mouse[!(isUnique(as.vector(name_mouse$initial_ensg))&isUnique(as.vector(name_mouse$ortholog_name))),]
#marker_plot_all_2=rabbit_id[rabbit_id%in%name_mouse_no$initial_ensg]
#name_rabbit_no=unique(as.vector(name_mouse_no$initial_ensg))
marker_plot_all_2=rabbit_id[!rabbit_id%in%name_mouse$initial_ensg]
name_rabbit_no=rabbit_id[!rabbit_id%in%name_mouse$initial_ensg]
ortogoli_name_final=c(name_rabbit,name_rabbit_no)
rabbit_id_final=c(marker_plot_all_1,marker_plot_all_2)
return(list(ortogoli_name_final,rabbit_id_final))}
```


```{r }
Test_Fisher=function(marker_all_cluster,marker_specific,background,cluster){
level=levels(as.factor(cluster))
p_value=rep(0,length(level))
odds_ratio=rep(0,length(level))
for (i in 1:length(level)){
show=build_fisher_test(marker_all_cluster[names(marker_all_cluster)==level[i]],marker_specific,background)
p_value[i]=as.numeric(show$p.value)
names(p_value)[i]=level[i]
odds_ratio[i]=as.numeric(show$estimate)
names(odds_ratio)[i]=level[i]
}
return(list(p_value,odds_ratio))
}

```



```{r }

setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/CIARA_archive/CIARA_old/inst/extdata")
load("knn_matrix_heart_new.Rda")
load("norm_data_heart.Rda")
load("raw_data_heart.Rda")
load("cluster_heart_small.Rda")
load("umap_cordinate_heart_small.Rda")


#load(system.file("extdata", "knn_matrix_heart_new.Rda", package ="CIARA"))
#load(system.file("extdata", "norm_data_heart.Rda", package ="CIARA"))
#load(system.file("extdata", "raw_data_heart.Rda", package ="CIARA"))
#load(system.file("extdata", "cluster_heart_small.Rda", package ="CIARA"))
#load(system.file("extdata", "umap_cordinate_heart_small.Rda", package ="CIARA"))


```

```{r }
#setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/published_data")
#load("heart_hyper_new.Rda")
#result_old=result
```


```{r }
#load(system.file("extdata", "heart_december_2021.Rda", package ="CIARA"))
#result_old=result
#ciara_genes_old=row.names(result_old)[result_old[,1]<1]
#geni_top=row.names(result_old)[result_old[,2]<0.0001&result_old[,1]==0]
#geni_top_top=row.names(result_old)[order(as.numeric(result_old[,2]))]
```

## Load 

Rscript --vanilla /home/ies/gabriele.lubatti/ciara_marco/Entropy_server_december_2021_easy.R -n norm_data_heart -k knn_matrix_heart_new -o endoderm_a.Rda -r 1 -l 3 -h 30 -t 1 -p 0.001 -c 10 -a TRUE

Rscript --vanilla /home/ies/gabriele.lubatti/ciara_marco/Entropy_server_december_2021_easy.R -n norm_data_heart -k knn_matrix_heart_new -o endoderm.Rda -r 1 -l 3 -h 30 -t 1 -p 0.001 -c 10 -a FALSE

```{r }
#setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/CIARA_archive/CIARA_old/inst/extdata")
#load("heart_december_2021.Rda")

```

```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/vignettes")
load("endoderm.Rda")
```


```{r }
ciara_genes_old=row.names(result)[result[,1]<1]
geni_top_top_old=row.names(result)[order(as.numeric(result[,1]))]
background_old=row.names(result)
```


```{r }
ciara_genes = ciara_genes_old
geni_top_top = geni_top_top_old
background = background_old
```


```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/vignettes")
load("endoderm_a.Rda")
```


```{r }
ciara_genes=row.names(result)[result[,1]<1]
geni_top_top=row.names(result)[order(as.numeric(result[,1]))]
background=row.names(result)
```


```{r}
#setwd('/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/elmir_data/heart_data')
gene_id=row.names(raw_data_heart)
#setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/elmir_data/heart_data")
#write.table(gene_id,file="geni_heart.txt",row.names = F,quote=F)
#setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/elmir_data/heart_data")

setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/CIARA_archive/CIARA_old/inst/extdata")
name_mouse=read.csv("human_mouse_heart.csv")
#name_mouse=read.csv(system.file("extdata", "human_mouse_heart.csv", package ="CIARA"))


human_gene_name=geni_ortogoli_unique(gene_id,name_mouse)
human_name_all=human_gene_name[[1]]
human_id_all=human_gene_name[[2]]

data_all_human=data.frame(human_id_all,human_name_all)
row.names(data_all_human)=human_id_all
data_all_human_new=data_all_human[gene_id,]
human_name_final=as.vector(data_all_human_new[,2])

row.names(norm_data_heart)=human_name_final

row.names(raw_data_heart)=human_name_final

ciara_genes=data_all_human[ciara_genes,2]

background=data_all_human[background,2]

#geni_top=data_all_human[geni_top,2]
geni_top_top=data_all_human[geni_top_top,2]

```

```{r }


p=list()
for(i in (geni_top_top)[1:10]){
  q=plot_gene(norm_data_heart,umap_cordinate_heart_small,i,i)
  p=list(p,q)
}
p
```





```{r }
plot_genes_sum(umap_cordinate_heart_small,norm_data_heart,(ciara_genes),"Sum from top CIARA genes")

```





```{r }

norm_counts_small = apply(norm_data_heart[(ciara_genes), ], 
        1, function(x) {
            y = x/sum(x)
            return(y)
        })
    gene_sum = apply(norm_counts_small, 1, sum)
    
    
genes_name_text=selection_localized_genes(norm_data_heart,ciara_genes,min_number_cells=4,max_number_genes=4)
plot.elmir=umap_cordinate_heart_small
colnames(plot.elmir)=c("UMAP_1","UMAP_2")
plot_interactive(plot.elmir,gene_sum,genes_name_text,min_x=NULL,max_x=NULL,min_y=NULL,max_y=NULL)
```

## Cluster analysis using ciara of mixing (step 2)
```{r }


heart_seurat_ciara=cluster_analysis_integrate_rare(raw_data_heart,"Elmir data",0.1,5,30,ciara_genes)

#heart_seurat_ciara_2=Cluster_analysis_integrate_rare(raw_data_heart,"Elmir data",0.1,3,30,ciara_genes_old)

#heart_seurat_ciara=heart_seurat_ciara_2
heart_seurat_ciara=FindClusters(heart_seurat_ciara,resolution = 0.2)

```

```{r }


find_resolution(heart_seurat_ciara,seq(0.1,1,0.1))
```

```{r }
heart_seurat_ciara=FindClusters(heart_seurat_ciara,resolution = 0.2)
```


```{r }
plot_umap(umap_cordinate_heart_small,heart_seurat_ciara$RNA_snn_res.0.2)
```


```{r}
names(cluster_heart_small)=colnames(raw_data_heart)
cluster_ciara_heart=as.vector(heart_seurat_ciara$RNA_snn_res.0.2)
names(cluster_ciara_heart)=colnames(raw_data_heart)
final_cluster_heart=merge_cluster(cluster_heart_small,cluster_ciara_heart,30)
```





```{r }
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_4/figure_4_e.pdf")
plot_umap(umap_cordinate_heart_small,final_cluster_heart)
dev.off()

```

```{r }

final_cluster_heart_new=final_cluster_heart
final_cluster_heart_new[final_cluster_heart=="2-step_2"]="Rare Endoderm"
final_cluster_heart_new[final_cluster_heart=="En1"]="Endoderm1"
final_cluster_heart_new[final_cluster_heart=="En2"]="Endoderm2"

pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figures_conference/umap_endoderm_conference.pdf",width = 8, height = 6)
p=plot_umap(umap_cordinate_heart_small,final_cluster_heart_new)
p[[1]]+theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),axis.text.y=element_blank(),
        axis.ticks.y=element_blank())+theme(text = element_text(size=18))
dev.off()

```

```{r }
table(final_cluster_heart)
```



```{r}
DefaultAssay(heart_seurat_ciara) <- "RNA"
markers_first_elmir=markers_cluster_seurat(heart_seurat_ciara,final_cluster_heart,names(heart_seurat_ciara$RNA_snn_res.0.1),50)


marker_heart_top=markers_first_elmir[[1]]
marker_heart=markers_first_elmir[[3]]
```

```{r}

top_heart=white_black_markers(final_cluster_heart,"2-step_2",norm_data_heart,marker_heart,0)
top_heart=names(top_heart)[top_heart]

mean_top_heart=apply(norm_data_heart[top_heart,final_cluster_heart=="2-step_2"],1,mean)
mean_top_heart=sort(mean_top_heart,decreasing = T)

top_heart=names(mean_top_heart)
names(top_heart)=rep("2-step_2",length(top_heart))
```

```{r}

plot_balloon_marker(norm_data_heart,final_cluster_heart,marker_heart_top,10,max_size=2,text_size=9)
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_4/figure_4_f.pdf")

plot_balloon_marker(norm_data_heart,final_cluster_heart,top_heart,40,max_size=2,text_size=9)
dev.off()
```









```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/CIARA_archive/CIARA_old/inst/extdata")
load("markers_first_elmir_final.Rda")
#load(system.file("extdata", "markers_first_elmir_final.Rda", package ="CIARA"))
#setwd("/Users/gabriele.lubatti/Desktop/Phd/ciara_of_mixing_library/elmir_data")
#load(file="markers_first_elmir_final.Rda")
marker_elmir_all=markers_first_elmir_final[[3]]
marker_endoderm_2=marker_elmir_all[names(marker_elmir_all)=="Endoderm_2"]





```





```{r }
result=Test_Fisher(marker_heart,marker_endoderm_2,as.vector(marker_heart),as.vector(final_cluster_heart))




names(result[[1]])[result[[1]]<0.05&result[[2]]>2]

geni_comuni=intersect(marker_heart[names(marker_heart)=="2-step_2"],marker_endoderm_2)
```

```{r }
plot_balloon_marker_here=function (norm_counts, cluster, marker_complete, max_number, 
    max_size = 5, text_size = 7) 
{
    livelli <- levels(factor(cluster))
    all_markers_plot <- rep(list(0), length(livelli))
    all_markers <- rep(list(0), length(livelli))
    for (i in 1:length(livelli)) {
        genes_4_0 <- marker_complete[(names(marker_complete) == 
            livelli[i])]
        if (length(genes_4_0) > 0) {
            genes_4_0 <- genes_4_0[1:max_number]
            all_markers[[i]] <- genes_4_0
            #genes_4_0_plot <- paste(livelli[i], genes_4_0, sep = "_")
            genes_4_0_plot <- genes_4_0
            all_markers_plot[[i]] <- genes_4_0_plot
        }
    }
    all_markers <- lapply(all_markers, function(x) {
        x[x != 0]
    })
    all_markers_plot <- lapply(all_markers_plot, function(x) {
        x[x != 0]
    })
    all_markers_values <- rep(list(0), length(livelli))
    for (i in 1:length(livelli)) {
        gene_values_0 <- apply(norm_counts[unlist(all_markers, 
            use.names = FALSE), cluster == livelli[i]], 1, mean)
        all_markers_values[[i]] <- gene_values_0
    }
    values <- rep(list(0), length(livelli))
    for (i in 1:length(livelli)) {
        valore <- apply(norm_counts[unlist(all_markers, use.names = FALSE), 
            cluster == livelli[i]], 1, function(x) {
            sum(x > 1)/length(x)
        })
        values[[i]] <- valore
    }
    cluster_label_all <- rep(list(0), length(livelli))
    for (i in 1:length(livelli)) {
        cluster_label_all[[i]] <- rep(livelli[i], length(unlist(all_markers)))
        #cluster_label_all[[i]] <- rep(livelli[i], length(unlist(all_markers)))
    }
    all_markers_plot <- unlist(all_markers_plot)
    cluster_label_all <- unlist(cluster_label_all)
    values <- unlist(values)
    all_markers_values <- unlist(all_markers_values)
    balloon_melted <- data.frame(all_markers_plot, cluster_label_all, 
        values)
    colnames(balloon_melted) <- c("all_markers_plot", "cluster_label_all", 
        "values")
    p <- ggplot2::ggplot(balloon_melted, ggplot2::aes(x = cluster_label_all, 
        y = all_markers_plot))
    p + ggplot2::geom_point(ggplot2::aes(size = values, colour = as.numeric(all_markers_values))) + 
        ggplot2::theme(panel.background = ggplot2::element_blank(), 
            panel.border = ggplot2::element_rect(colour = "blue", 
                fill = NA, size = 3)) + ggplot2::scale_size_area(max_size = max_size) + 
        ggplot2::scale_colour_gradient(low = "white", high = "midnight blue", 
            na.value = NA) + ggplot2::labs(colour = "Mean", 
        size = "Value") + 
        ggplot2::xlab("Cluster") + ggplot2::ylab("Markers") + 
        ggplot2::theme(text = ggplot2::element_text(size = text_size), 
            axis.text.x = ggplot2::element_text(angle = 45, vjust = 1, 
                hjust = 1,size=14), axis.title.x = ggplot2::element_blank())
}
```


```{r }
names(geni_comuni)=rep("Rare Endoderm",length(geni_comuni))
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figures_conference/marker_endoderm_conference.pdf",width = 8, height = 6)
plot_balloon_marker_here(norm_data_heart,final_cluster_heart_new,geni_comuni,10,max_size=8,text_size=18)
dev.off()
```


```{r }

listInput <- list(mouse_rare_endoderm=marker_heart[names(marker_heart)=="2-step_2"],human_rare_endoderm=marker_endoderm_2)
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_4/figure_4_g.pdf")
upset(fromList(listInput), order.by = "freq")
dev.off()

#listInput <- list(ciara_mixing_rare_2=marker_2_small,giniclust2_rare_2=marker_2_original)

#upset(fromList(listInput), order.by = "freq")









```




```{r }
p=list()
for(i in (geni_comuni)[1:10]){
  q=plot_gene(norm_data_heart,umap_cordinate_heart_small,i,i)
  p=list(p,q)
}
p
```


