---
title: "mouse_esc"
author: "Gabriele Lubatti"
date: "10/22/2021"
output: html_document
---


```{r } 
gc()
rm(list=ls())
#library(devtools)
#install_github("ScialdoneLab/IDENTOM",auth_token="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",ref="master")
```


```{r } 
#library(Biobase)
#library(Seurat)
#library(clustree)
#library(plotly)
#library(ggplot2)
library(IDENTOM)
library(UpSetR)
```


```{r }

Plot_qc_cluster=function(seurat_object,cluster,mit_prefix,rib_prefix_1,rib_prefix_2){

raw_counts<- (GetAssayData(seurat_object, slot = "counts",assay="RNA"))
sum_umi=apply(raw_counts,2,sum)
sum_geni=apply(raw_counts,2,function(x){
  x=x[x!=0]
  return(length(x))
})


frac_mito=apply(raw_counts,2,function(x){
  #return(sum(x[grep("MT-",row.names(raw_counts))])/sum(x))
  return(sum(x[grep(mit_prefix,row.names(raw_counts))])/sum(x))
  
  
  
})


frac_ribo=apply(raw_counts,2,function(x){
  #frac_ribo_s=x[grep("RPS",row.names(raw_counts))]
  #frac_ribo_l=x[grep("RPL",row.names(raw_counts))]
  frac_ribo_s=x[grep(rib_prefix_1,row.names(raw_counts))]
  frac_ribo_l=x[grep(rib_prefix_2,row.names(raw_counts))]
  frac_ribo_all=c(frac_ribo_s,frac_ribo_l)
  return(sum(frac_ribo_all)/sum(x))



})


Cluster=as.factor(cluster)

data_plot=data.frame(as.numeric(frac_mito),as.numeric(sum_geni),as.numeric(sum_umi),as.numeric(frac_ribo),Cluster)

library(ggplot2)

plot_1=ggplot(data_plot, aes(x=Cluster, y=frac_mito,fill=Cluster)) + 
  geom_boxplot()+xlab("clusters")+ylab("frac mitochindrial reads")+ggtitle("Frac mito reads")


plot_2=ggplot(data_plot, aes(x=Cluster, y=sum_umi,fill=Cluster)) + 
  geom_boxplot()+xlab("clusters")+ylab("UMI counts")+ggtitle("UMI counts")

plot_3=ggplot(data_plot, aes(x=Cluster, y=sum_geni,fill=Cluster)) + 
  geom_boxplot()+xlab("clusters")+ylab("Number of genes")+labs(color="Cluster")+ggtitle("Number of genes")

plot_4=ggplot(data_plot, aes(x=Cluster, y=frac_ribo,fill=Cluster)) + 
  geom_boxplot()+xlab("clusters")+ylab("Frac ribosomial reads")+labs(color="Cluster")+ggtitle("Frac ribosomial reads")
return (list(plot_1,plot_2,plot_3,plot_4))
}

```

```{r}
Cluster_analysis_integrate_rare_update=function (raw_counts, batch_name_1, resolution, neighbors, max_dimension, 
    feature_genes = NULL) 
{
    batch_1 <- CreateSeuratObject(counts = raw_counts, project = batch_name_1)
    batch_1 <- subset(batch_1, subset = nFeature_RNA > 0)
    batch_1 <- NormalizeData(batch_1, verbose = FALSE)
    batch_1 <- FindVariableFeatures(batch_1, selection.method = "vst", 
        nfeatures = 2000)
    batch_combined = batch_1
    #batch_combined <- ScaleData(batch_combined, verbose = FALSE)
    batch_combined$frac_mito=frac_mito
batch_combined$frac_ribo=frac_ribo
batch_combined <- ScaleData(batch_combined, verbose = FALSE,vars.to.regress = c("nCount_RNA","frac_mito","frac_ribo"))
    batch_combined <- RunPCA(batch_combined, npcs = max_dimension, 
        verbose = FALSE, features = feature_genes)
    batch_combined = RunUMAP(batch_combined, reduction = "pca", 
        dims = 1:20, set.seed = 42)
    batch_combined <- FindNeighbors(batch_combined, reduction = "pca", 
        dims = 1:max_dimension, k.param = neighbors)
    batch_combined <- FindClusters(batch_combined, resolution = resolution)
    return(batch_combined)
}
```

##Start with dataset at 0h

# Start here
```{r}
setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
load(file='mayra_dati_raw_0.Rda')
mayra_seurat_0=Cluster_analysis_integrate_rare(mayra_dati_raw_0,"Mayra_data_0",0.1,5,30)
#norm_counts_ane_0=as.matrix(GetAssayData(mayra_seurat_0, slot = "data",assay="RNA"))
#knn_matrix_ane_0=as.matrix(mayra_seurat_0@graphs$RNA_nn)

load("knn_matrix_ane_0.Rda")
load("norm_counts_ane_0.Rda")
#setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
#load("entropy_ane_0.Rda")
cordinate_umap_0=as.data.frame(Embeddings(mayra_seurat_0, reduction = "umap")[, 1:2])
```

```{r }
Plot_gene(norm_counts_ane_0,cordinate_umap_0,"Zscan4d","Zscan4d")
```

#new run entropy of mixing  (1285 cells)
```{r }
#setting srun -p normal_q -c 10  --mem=100G -t 1:00:00 --pty bash
##
#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_server_december_2021_easy.R -n norm_counts_ane_0 -k knn_matrix_ane_0 -o ane_0_december_2021.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001 -c 10 -a FALSE


#Time difference of 4.450016 mins 50.2696 secs

#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_server_december_2021_easy.R -n norm_counts_ane_0 -k knn_matrix_ane_0 -o ane_0_december_2021_fast.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001 -c 10 -a TRUE

#Time difference of 50.2696 secs

```

```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
load("ane_0_december_2021.Rda")
complete=result
entropy_genes_complete=row.names(complete)[complete[,1]<1]
```
```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
load("ane_0_december_2021_fast.Rda")
small=result
entropy_genes_small=row.names(small)[small[,1]<1]
```

```{r }
find_jacardi_genes=function(entropy_mixing_old,entropy_mixing_new){
unione=union(entropy_mixing_old,entropy_mixing_new)
intersezione=intersect(entropy_mixing_old,entropy_mixing_new)

jacardi=length(intersezione)/length(unione)
print(jacardi)
return(jacardi)
}

```

```{r }
find_jacardi_genes(entropy_genes_complete,entropy_genes_small)
```


```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
load("ane_0_december_2021.Rda")
entropy_genes=row.names(result)[result[,1]<1]
geni_top_top=row.names(result)[order(as.numeric(result[,1]))]
```

```{r }
background=row.names(result)
```

```{r }
library(ggplot2)
p=list()
for(i in (geni_top_top)[1:10]){
  q=Plot_gene(norm_counts_ane_0,cordinate_umap_0,i,i)
  p=list(p,q)
}
p
```

```{r }
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_1/figure_1_b_ggplot_first.pdf")
Plot_gene(norm_counts_ane_0,cordinate_umap_0,geni_top_top[1],geni_top_top[1])
dev.off()
pdf("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/figures_paper/figure_1/figure_1_b_ggplot_last.pdf")
Plot_gene(norm_counts_ane_0,cordinate_umap_0,geni_top_top[length(geni_top_top)],geni_top_top[length(geni_top_top)])
dev.off()
```

##Start with dataset at 24 h


#new run entropy of mixing
```{r }
##LAST VERSION condition srun -p normal_q -c 10 --mem=100G -t 1:00:00 --pty bash
#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_server_december_2021_easy.R -n norm_counts_ane_24_update -k knn_matrix_ane_24_update -o ane_december_2021.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001 -c 10 -a FALSE

#  Time difference of Time difference of 1.506383 mins 


#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_server_december_2021_easy.R -n norm_counts_ane_24_update -k knn_matrix_ane_24_update -o ane_december_2021_a.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001 -c 10 -a TRUE

# Time difference of 17.48768 secs

```

```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
load("ane_december_2021.Rda")
```

```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
load("ane_0_december_2021.Rda")
```

```{r }

load(system.file("extdata", "raw_counts_ane_24_update.Rda", package ="IDENTOM"))


```


```{r }
#load("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project/final_cluster_version_sub.Rda")
```


```{r }
mayra_seurat_24=Cluster_analysis_integrate_rare(raw_counts_ane_24_update,"Mayra_data_24",0.1,5,30)
Plot_qc_cluster(mayra_seurat_24,as.vector(mayra_seurat_24$RNA_snn_res.0.1),"mt-","Rps","Rpl")
```

```{r }
#norm_counts_ane_24=as.matrix(GetAssayData(mayra_seurat_24, slot = "data",assay="RNA"))

cordinate_umap_24=as.data.frame(Embeddings(mayra_seurat_24, reduction = "umap")[, 1:2])
Plot_umap(cordinate_umap_24,mayra_seurat_24$RNA_snn_res.0.1)
```


```{r }

frac_mito=apply(raw_counts_ane_24_update,2,function(x){
  #return(sum(x[grep("MT-",row.names(raw_counts))])/sum(x))
  return(sum(x[grep("mt-",row.names(raw_counts_ane_24_update))])/sum(x))
  
  
  
})


frac_ribo=apply(raw_counts_ane_24_update,2,function(x){
  #frac_ribo_s=x[grep("RPS",row.names(raw_counts))]
  #frac_ribo_l=x[grep("RPL",row.names(raw_counts))]
  frac_ribo_s=x[grep("Rps",row.names(raw_counts_ane_24_update))]
  frac_ribo_l=x[grep("Rpl",row.names(raw_counts_ane_24_update))]
  frac_ribo_all=c(frac_ribo_s,frac_ribo_l)
  return(sum(frac_ribo_all)/sum(x))



})
```


```{r }
mayra_seurat_24_update=Cluster_analysis_integrate_rare_update(raw_counts_ane_24_update,"Mayra_data_24",0.1,5,30)
norm_counts_ane_24_update=as.matrix(GetAssayData(mayra_seurat_24_update, slot = "data",assay="RNA"))
knn_matrix_ane_24_update=as.matrix(mayra_seurat_24_update@graphs$RNA_nn)
cordinate_umap_24_update=as.data.frame(Embeddings(mayra_seurat_24_update, reduction = "umap")[, 1:2])
```



```{r}

initial_cluster_24=as.vector(mayra_seurat_24_update$RNA_snn_res.0.1)
mayra_seurat_24_update=FindClusters(mayra_seurat_24_update,resolution = 0.2)
initial_cluster_24_2=as.vector(mayra_seurat_24_update$RNA_snn_res.0.2)

```
```{r}
Plot_umap(cordinate_umap_24_update,initial_cluster_24)
```



##Old run entropy mixing
```{r }
## New entropy of mixing
#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_hyper_server.R -n #norm_counts_ane_24_update -k knn_matrix_ane_24_update -o ane_hyper.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001


#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_hyper_server_all_cells.R -n norm_counts_ane_24_update -k knn_matrix_ane_24_update -o ane_hyper_old.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001
#Time difference of 1.501484 mins

#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_hyper_server_final.R -n norm_counts_ane_24_update -k knn_matrix_ane_24_update -o ane_hyper_old_all.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001 -a FALSE

#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_hyper_server_blood_new.R -n norm_counts_ane_24_update -k knn_matrix_ane_24_update -o ane_hyper_new.Rda -r 1 -l 3 -h 20 -t 1 -p 
#0.001
#Time difference of Time difference of 17.48768 secs
```

#old run entropy of mixing
```{r }
#setting srun -p normal_q -c 10  --mem=10G -t 1:00:00 --pty bash
##LAST VERSION condition srun -p normal_q -c 10 --mem=10G -t 1:00:00 --pty bash
#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_server_december_2021_new.R -n norm_counts_ane_24_update -k knn_matrix_ane_24_update -o ane_december_2021.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001 -c 10 -a FALSE


#Time difference of 2.995655 mins 

#Rscript --vanilla /home/ies/gabriele.lubatti/entropy_mixing/ane_data/Entropy_server_december_2021_new.R -n norm_counts_ane_24_update -k knn_matrix_ane_24_update -o ane_december_2021_a.Rda -r 1 -l 3 -h 20 -t 1 -p 0.001 -c 10 -a TRUE

#Time difference of 29.24131 secs

```

```{r }

#load(system.file("extdata", "ane_december_2021.Rda", package ="IDENTOM"))


```




```{r }
#entropy_genes=row.names(result)[result[,1]<1]
#geni_top=row.names(result)[result[,2]<0.000001&result[,1]==0]

#geni_top_top=row.names(result)[order(as.numeric(result[,2]))]
```


```{r }
setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
load("ane_0_december_2021.Rda")
```

```{r }
load("/Users/gabriele.lubatti/Desktop/Phd/entropy_of_mixing_library/github_january_2022/ane_december_2021.Rda")
```

```{r }
entropy_genes=row.names(result)[result[,1]<1]
geni_top=row.names(result)[result[,1]==0&result[,2]<0.0001]
geni_top_top=row.names(result)[order(as.numeric(result[,2]))]
```

```{r }
background=row.names(result)
```

```{r }
library(ggplot2)
p=list()
for(i in (geni_top_top)[1:10]){
  q=Plot_gene(norm_counts_ane_24_update,cordinate_umap_24_update,i,i)
  p=list(p,q)
}
p
```

```{r }
Plot_gene(norm_counts_ane_24_update,cordinate_umap_24_update,geni_top_top[length(geni_top_top)],geni_top_top[length(geni_top_top)])
```


```{r }
Plot_gene(norm_counts_ane_24_update,cordinate_umap_24_update,"Gata6","Gata6")
```


```{r }

Plot_genes_sum(cordinate_umap_24_update,norm_counts_ane_24_update,(geni_top),"Sum from top entropy genes")

```





```{r }
norm_counts_small = apply(norm_counts_ane_24_update[(geni_top), ], 
        1, function(x) {
            y = x/sum(x)
            return(y)
        })
    gene_sum = apply(norm_counts_small, 1, sum)
    
    
genes_name_text=selection_localized_genes(norm_counts_ane_24_update,geni_top,min_number_cells=4,max_number_genes=4)
plot.elmir=cordinate_umap_24_update
colnames(plot.elmir)=c("UMAP_1","UMAP_2")
library(plotly)
interactive_plot(plot.elmir,gene_sum,genes_name_text,min_x=NULL,max_x=NULL,min_y=NULL,max_y=NULL)
```



## Cluster analysis using entropy of mixing (step 2)

```{r }
#mayra_seurat_entropy_24=Cluster_analysis_integrate_rare(mayra_dati_raw_24,"24h",0.01,5,30,names(entro#py_genes))
mayra_seurat_entropy_24=Cluster_analysis_integrate_rare_update(raw_counts_ane_24_update,"24h",0.1,3,30,(entropy_genes))


#mayra_seurat_entropy_24_2=Cluster_analysis_integrate_rare_update(raw_counts_ane_24_update,"24h",0.1,5,30,(entropy_genes))

#mayra_seurat_entropy_24=FindClusters(mayra_seurat_entropy_24,resolution = 0.1)

```


```{r }
find_resolution(mayra_seurat_entropy_24,seq(0.1,0.5,0.1))
```



```{r }

#mayra_seurat_entropy_24=mayra_seurat_entropy_24_2
#mayra_seurat_entropy_24=FindClusters(mayra_seurat_entropy_24,resolution = 0.2)

norm_mayra_entropy_24=as.matrix(GetAssayData(mayra_seurat_entropy_24, slot = "data",assay="RNA"))



cordinate_umap_24_entropy=as.data.frame(Embeddings(mayra_seurat_entropy_24, reduction = "umap")[, 1:2])


```


```{r }
Plot_umap(cordinate_umap_24_entropy,mayra_seurat_entropy_24$RNA_snn_res.0.1)
```

```{r}
table(mayra_seurat_entropy_24$RNA_snn_res.0.1)
```

```{r }
Plot_umap(cordinate_umap_24_update,mayra_seurat_entropy_24$RNA_snn_res.0.1)
```

```{r }
cluster_original=as.vector(mayra_seurat_24_update$RNA_snn_res.0.1)
names(cluster_original)=names(mayra_seurat_24_update$RNA_snn_res.0.1)
cluster_sub=as.vector(mayra_seurat_entropy_24$RNA_snn_res.0.1)
names(cluster_sub)=names(mayra_seurat_entropy_24$RNA_snn_res.0.1)
final_cluster_version_sub=merge_cluster(cluster_original,cluster_sub,20)
```



```{r }
Plot_umap(cordinate_umap_24_update,final_cluster_version_sub)
```
```{r}
DefaultAssay(mayra_seurat_24_update) <- "RNA"
markers_first_elmir=markers_first_method(mayra_seurat_24_update,final_cluster_version_sub,names(mayra_seurat_24_update$RNA_snn_res.0.1),20)
```



```{r}
marker_plot_day_24_first=markers_first_elmir[[1]]

marker_plot_plot_day_24_first=markers_first_elmir[[2]]
marker_all_day_24_first=markers_first_elmir[[3]]

```

```{r }
top_1=white_black_marker(final_cluster_version_sub,"1-step_2",norm_counts_ane_24_update,marker_all_day_24_first,0)

top_1=names(top_1)[top_1]

mean_top_1=apply(norm_counts_ane_24_update[top_1,final_cluster_version_sub=="1-step_2"],1,mean)
mean_top_1=sort(mean_top_1,decreasing = T)

top_1=names(mean_top_1)
names(top_1)=rep("1-step_2",length(top_1))
```

```{r }
top_2=white_black_marker(final_cluster_version_sub,"2-step_2",norm_counts_ane_24_update,marker_all_day_24_first,0)
top_2=names(top_2)[top_2]

mean_top_2=apply(norm_counts_ane_24_update[top_2,final_cluster_version_sub=="2-step_2"],1,mean)
mean_top_2=sort(mean_top_2,decreasing = T)

top_2=names(mean_top_2)
names(top_2)=rep("2-step_2",length(top_2))
```

```{r }

Plot_balons(norm_counts_ane_24_update,final_cluster_version_sub,top_1,30,max_size=5,text_size=10)

#Plot_balons(norm_counts_ane_24_update,final_cluster_version_sub,marker_all_day_24_first[names(marker_all_day_24_first)=="1-step_2"],30,max_size=5,text_size=10)

Plot_balons(norm_counts_ane_24_update,final_cluster_version_sub,top_2,30,max_size=5,text_size=10)

#Plot_balons(norm_counts_ane_24_update,final_cluster_version_sub,marker_all_day_24_first[names(marker_all_day_24_first)=="2-step_2"],30,max_size=5,text_size=10)

```
```{r}


white_black_7=white_black_marker(final_cluster_version_sub,"1-step_2",norm_counts_ane_24_update,marker_all_day_24_first,0)
sum(white_black_7)

white_black_7=white_black_marker(final_cluster_version_sub,"2-step_2",norm_counts_ane_24_update,marker_all_day_24_first,0)
sum(white_black_7)

```


## Marker at 48h


```{r}
setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
cluster_mayra=read.csv('LIFcells_leidenClustering.csv')
cluster_mayra_48=cluster_mayra[as.vector(cluster_mayra$batch)=='48h',]
#row.names(cluster_mayra_48)=as.vector(cluster_mayra_48$cell)
#cell_name=as.vector(cluster_mayra_48$cell)
cluster_number_48=(cluster_mayra_48$cluster)
cluster_number_48=as.character(cluster_number_48)
#cell_name_new=substring(cell_name,1,nchar(cell_name)-5)

```



```{r}
#setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
#load(file='mayra_dati_raw_48.Rda')
load(system.file("extdata", "mayra_dati_raw_48.Rda", package ="IDENTOM"))
mayra_seurat_48=Cluster_analysis_integrate_rare(mayra_dati_raw_48,"Mayra_data_48",0.1,5,30)
norm_counts_ane_48=as.matrix(GetAssayData(mayra_seurat_48, slot = "data",assay="RNA"))
knn_matrix_ane_48=as.matrix(mayra_seurat_48@graphs$RNA_nn)
```


```{r}
#setwd("/Users/gabriele.lubatti/Desktop/Phd/Early_embryonic_like_cells/Mayra_project")
#load(file='mayra_dati_raw_48.Rda')

cordinate_umap_48=as.data.frame(Embeddings(mayra_seurat_48, reduction = "umap")[, 1:2])
```




```{r}
DefaultAssay(mayra_seurat_48) <- "RNA"
markers_first_elmir_48=markers_first_method(mayra_seurat_48,cluster_number_48,names(mayra_seurat_48$RNA_snn_res.0.1),20)
```



```{r}

marker_all_day_48_first=markers_first_elmir_48[[3]]

marker_1_small=marker_all_day_48_first[names(marker_all_day_48_first)==5]

marker_all_day_24_first_2=marker_all_day_24_first[names(marker_all_day_24_first)=="2-step_2"]

```


```{r }
Function_fisher=function(a,b,c){
matrice=matrix(c(sum(c[c%in%a]%in%c[c%in%b]),sum(c[c%in%a]%in%c[!c%in%b]),sum(c[!c%in%a]%in%c[c%in%b]),sum(c[!c%in%a]%in%c[!c%in%b])),nrow=2,ncol=2,byrow = T)
#Fisher test
fisher.test(matrice)
}
```

```{r}
Test_Fisher=function(entropy_cluster,markers_cluster,marker_top){
level=levels(as.factor(entropy_cluster))
p_value=rep(0,length(level))
odds_ratio=rep(0,length(level))
set_1=marker_top
for (i in 1:length(level)){
  set_2=markers_cluster[names(markers_cluster)==level[i]]
set_all=markers_cluster
show=Function_fisher(set_1,set_2,set_all)

p_value[i]=as.numeric(show$p.value)
names(p_value)[i]=level[i]
odds_ratio[i]=as.numeric(show$estimate)
names(odds_ratio)[i]=level[i]
}
return(list(p_value,odds_ratio))
}
test=Test_Fisher(final_cluster_version_sub,marker_all_day_24_first,marker_1_small)
test[[2]][test[[1]]<0.05&test[[2]]>2]
```

```{r }

listInput <- list(mouse_48h_differentiation=marker_1_small,mouse_24h_differentiation=marker_all_day_24_first_2)

upset(fromList(listInput), order.by = "freq")










```



